version: "3.9"

name: avaliacao-ii

services:
  postgres:
    image: postgres:16-alpine
    container_name: pg_avaliacao
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-avaliacao2}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-avaliacao2}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # opcional: se quiser usar arquivo .env dedicado
    # env_file:
    #   - .env

volumes:
  pg_data:
    name: pg_data_avaliacao